### ISSUE TITLE
`UC006`: Bixi Trip Duration Analysis in `PyTransit-Microservices`

### ISSUE THREAD

**Issue by k-allagbe** [Monitoring-Mtl/PyTransit-MicroServices#80]
## Feature Request

**Description:**

Design and implement an ETL pipeline to calculate the average trip duration within the Bixi network.

**Use Case:**

Monitoring-Mtl/Frontend#114

**Proposed Solution:**

- Extract: Automated yearly historic data extraction from [Bixi Open data](https://bixi.com/en/open-data/)
- Transform: Apply Pandas for data cleaning and transformation, calculating average trip durations and handling anomalies or missing data
- Load: Store the processed data in a cloud hosted MongoDB

**Alternative Solutions:**

PostgresSQL with a yearly cron job for data extraction and simple or materialized views for transformations. Could become costly on budget in our AWS ecosystem with the use of RDS.

**Additional Information:**

NA

## Checklist

- [x] I have searched for existing feature requests that are similar.
- [x] I have provided a clear and concise description of the feature.
- [x] I have explained the use case for the feature.
- [x] I have considered possible implementation approaches.

## Tasks

- [x] #86 
- [x] #90
- [x] Documentation
